# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The phrase text', max_length=500, verbose_name='Text field')),
                ('language_code', models.CharField(help_text='The ISO639-1 language code', max_length=10, verbose_name='Language code')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.ForeignKey(help_text='Phrase input for translation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputted', to='translation.Phrase', verbose_name='Input text')),
                ('translated_text', models.ForeignKey(help_text='Phrase translation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated', to='translation.Phrase', verbose_name='Translated text')),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='translation',
            field=models.ManyToManyField(help_text='The translation relations for this phrase', related_name='translations', through='translation.TranslateEvent', to='translation.Phrase', verbose_name='Phrase translation'),
        ),
    ]
