# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the language', max_length=100, verbose_name='Language name')),
                ('language_code', models.CharField(help_text='The ISO639-1 language code', max_length=10, verbose_name='Language code')),
            ],
        ),
    ]
