# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:46
from __future__ import unicode_literals

from django.db import migrations


def get_languages():
    '''
    Returns list of languages taken from google api.
    '''
    return [
                {'name': 'Afrikaans', 'language': 'af'},
                {'name': 'Albanian', 'language': 'sq'},
                {'name': 'Amharic', 'language': 'am'},
                {'name': 'Arabic', 'language': 'ar'},
                {'name': 'Armenian', 'language': 'hy'},
                {'name': 'Azerbaijani', 'language': 'az'},
                {'name': 'Basque', 'language': 'eu'},
                {'name': 'Belarusian', 'language': 'be'},
                {'name': 'Bengali', 'language': 'bn'},
                {'name': 'Bosnian', 'language': 'bs'},
                {'name': 'Bulgarian', 'language': 'bg'},
                {'name': 'Catalan', 'language': 'ca'},
                {'name': 'Cebuano', 'language': 'ceb'},
                {'name': 'Chichewa', 'language': 'ny'},
                {'name': 'Chinese (Simplified)', 'language': 'zh'},
                {'name': 'Chinese (Traditional)', 'language': 'zh-TW'},
                {'name': 'Corsican', 'language': 'co'},
                {'name': 'Croatian', 'language': 'hr'},
                {'name': 'Czech', 'language': 'cs'},
                {'name': 'Danish', 'language': 'da'},
                {'name': 'Dutch', 'language': 'nl'},
                {'name': 'English', 'language': 'en'},
                {'name': 'Esperanto', 'language': 'eo'},
                {'name': 'Estonian', 'language': 'et'},
                {'name': 'Filipino', 'language': 'tl'},
                {'name': 'Finnish', 'language': 'fi'},
                {'name': 'French', 'language': 'fr'},
                {'name': 'Frisian', 'language': 'fy'},
                {'name': 'Galician', 'language': 'gl'},
                {'name': 'Georgian', 'language': 'ka'},
                {'name': 'German', 'language': 'de'},
                {'name': 'Greek', 'language': 'el'},
                {'name': 'Gujarati', 'language': 'gu'},
                {'name': 'Haitian Creole', 'language': 'ht'},
                {'name': 'Hausa', 'language': 'ha'},
                {'name': 'Hawaiian', 'language': 'haw'},
                {'name': 'Hebrew', 'language': 'iw'},
                {'name': 'Hindi', 'language': 'hi'},
                {'name': 'Hmong', 'language': 'hmn'},
                {'name': 'Hungarian', 'language': 'hu'},
                {'name': 'Icelandic', 'language': 'is'},
                {'name': 'Igbo', 'language': 'ig'},
                {'name': 'Indonesian', 'language': 'id'},
                {'name': 'Irish', 'language': 'ga'},
                {'name': 'Italian', 'language': 'it'},
                {'name': 'Japanese', 'language': 'ja'},
                {'name': 'Javanese', 'language': 'jw'},
                {'name': 'Kannada', 'language': 'kn'},
                {'name': 'Kazakh', 'language': 'kk'},
                {'name': 'Khmer', 'language': 'km'},
                {'name': 'Korean', 'language': 'ko'},
                {'name': 'Kurdish (Kurmanji)', 'language': 'ku'},
                {'name': 'Kyrgyz', 'language': 'ky'},
                {'name': 'Lao', 'language': 'lo'},
                {'name': 'Latin', 'language': 'la'},
                {'name': 'Latvian', 'language': 'lv'},
                {'name': 'Lithuanian', 'language': 'lt'},
                {'name': 'Luxembourgish', 'language': 'lb'},
                {'name': 'Macedonian', 'language': 'mk'},
                {'name': 'Malagasy', 'language': 'mg'},
                {'name': 'Malay', 'language': 'ms'},
                {'name': 'Malayalam', 'language': 'ml'},
                {'name': 'Maltese', 'language': 'mt'},
                {'name': 'Maori', 'language': 'mi'},
                {'name': 'Marathi', 'language': 'mr'},
                {'name': 'Mongolian', 'language': 'mn'},
                {'name': 'Myanmar (Burmese)', 'language': 'my'},
                {'name': 'Nepali', 'language': 'ne'},
                {'name': 'Norwegian', 'language': 'no'},
                {'name': 'Pashto', 'language': 'ps'},
                {'name': 'Persian', 'language': 'fa'},
                {'name': 'Polish', 'language': 'pl'},
                {'name': 'Portuguese', 'language': 'pt'},
                {'name': 'Punjabi', 'language': 'pa'},
                {'name': 'Romanian', 'language': 'ro'},
                {'name': 'Russian', 'language': 'ru'},
                {'name': 'Samoan', 'language': 'sm'},
                {'name': 'Scots Gaelic', 'language': 'gd'},
                {'name': 'Serbian', 'language': 'sr'},
                {'name': 'Sesotho', 'language': 'st'},
                {'name': 'Shona', 'language': 'sn'},
                {'name': 'Sindhi', 'language': 'sd'},
                {'name': 'Sinhala', 'language': 'si'},
                {'name': 'Slovak', 'language': 'sk'},
                {'name': 'Slovenian', 'language': 'sl'},
                {'name': 'Somali', 'language': 'so'},
                {'name': 'Spanish', 'language': 'es'},
                {'name': 'Sundanese', 'language': 'su'},
                {'name': 'Swahili', 'language': 'sw'},
                {'name': 'Swedish', 'language': 'sv'},
                {'name': 'Tajik', 'language': 'tg'},
                {'name': 'Tamil', 'language': 'ta'},
                {'name': 'Telugu', 'language': 'te'},
                {'name': 'Thai', 'language': 'th'},
                {'name': 'Turkish', 'language': 'tr'},
                {'name': 'Ukrainian', 'language': 'uk'},
                {'name': 'Urdu', 'language': 'ur'},
                {'name': 'Uzbek', 'language': 'uz'},
                {'name': 'Vietnamese', 'language': 'vi'},
                {'name': 'Welsh', 'language': 'cy'},
                {'name': 'Xhosa', 'language': 'xh'},
                {'name': 'Yiddish', 'language': 'yi'},
                {'name': 'Yoruba', 'language': 'yo'},
                {'name': 'Zulu', 'language': 'zu'}
            ]


def language_bulk_create(apps, schema_editor):
    '''
    Bulk create language objects.
    '''
    Language = apps.get_model('translation', 'Language')

    objs = [
        Language(
            name=language['name'],
            language_code=language['language']
        ) for language in get_languages()
    ]

    Language.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_language'),
    ]

    operations = [
        migrations.RunPython(language_bulk_create)
    ]
