# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_create_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='language',
            field=models.ForeignKey(blank=True, help_text='The phrase language', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='translation.Language', verbose_name='Phrase language'),
        ),
    ]
