# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 00:16
from __future__ import unicode_literals

from django.db import migrations


def populate_language_field(apps, schema_editor):
    '''
    Populate FK language field in Phrase with Language object.
    '''
    Phrase = apps.get_model('translation', 'Phrase')
    Language = apps.get_model('translation', 'Language')

    for phrase in Phrase.objects.all():
        # get language code from the phrase
        language_code = phrase.language_code

        # set language foreign key in phrase.
        phrase.language = Language.objects.get(language_code=language_code)

        phrase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_phrase_language'),
    ]

    operations = [
        migrations.RunPython(populate_language_field)
    ]
