# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_remove_phrase_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.ForeignKey(help_text='The phrase language', on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='translation.Language', verbose_name='Phrase language'),
        ),
    ]
