# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_auto_20170109_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language_code',
            new_name='code',
        ),
    ]
