# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_auto_20170109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateevent',
            name='input_text',
            field=models.ForeignKey(default=1, help_text='Phrase input for translation', on_delete=django.db.models.deletion.PROTECT, related_name='inputted', to='translation.Phrase', verbose_name='Input text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translateevent',
            name='translated_text',
            field=models.ForeignKey(default=2, help_text='Phrase translation', on_delete=django.db.models.deletion.PROTECT, related_name='translated', to='translation.Phrase', verbose_name='Translated text'),
            preserve_default=False,
        ),
    ]
